### ISSUE TITLE
flameshot snap not run in linuxmint 19.1

### ISSUE THREAD

**Issue by Lvaskz** [flameshotapp/packages#6]
Hi, I am using linuxmint 19.1 cinnamon, 4.0.9, 64 bits.
I installed flameshot via Snapstore, after installed y tried to run it but is not working

**Comment by joshirio** [comment]
It also doesn't run on Ubuntu 18.04
![Bildschirmfoto vom 2019-03-10 16-12-03](https://user-images.githubusercontent.com/12795018/54087032-68214900-434f-11e9-8c55-bd934682bb78.png)

The issue is translated as: "Desktop file does not provide an 'exec' field"
I guess the `Exec=flameshot` is the problemhere because snap makes the command available under `flameshot-app.flameshot`. I think snap only creates an alias for flameshot if the name is flameshot.flameshot or if no other command on the system uses flameshot (for example if the deb is also installed).

Flameshot is running from snap when launched manually:
```
$ flameshot-app.flameshot 
Gtk-Message: Failed to load module "gail"
Gtk-Message: Failed to load module "atk-bridge"
Gtk-Message: Failed to load module "canberra-gtk-module"
Qt: Session management error: None of the authentication protocols specified are supported
```
Another issue is that the tray icon is there but the icon is empty, maybe it doesn't find the resource icon file.

**Comment by thomasleveil** [comment]
`snap refresh flameshot-app --edge` fixed this for me. It installed `v0.6.0+git63.19d7010 2019-09-04`

**Comment by Lvaskz** [comment]
> It installed `v0.6.0+git63.19d7010 2019-09-04`

I can confirm, it works except by language system (  I am using spanish, it is not translated)

**Comment by Bashar** [comment]
`snap refresh flameshot --edge` fixed it for me (after installing lameshot (edge) v0.8.5+git264.95d8920 from Jeremy Borgman (borgman-jeremy) refreshed)

ubuntu 20.04 installation from ubuntu software i got the error "Qt: Session management error: None of the authentication protocols specified are supported"

**Comment by mmahmoudian** [comment]
Considering the massive updates and fixes happened since August 2020 and new Snap, Flatpak and AppImage, I will close this issue as it was opened 2 years ago and based on the latest comment and my own tests it works.

In case you have any issues with Snap, please open a new issue.
